services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - ./db_data/pueblosmalaga.sql:/docker-entrypoint-initdb.d/pueblosmalaga.sql:ro

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
    container_name: elasticsearch_container
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    restart: always

  backend:
    build:
      context: ./backend
    container_name: flask_backend
    depends_on:
      - mysql
      - elasticsearch
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=1
